version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .Dockerfile
      target: production
    command: node ./build/app.js
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/web-scraper
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - web-scraper

  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: web-scraper
    networks:
      - web-scraper

volumes:
  db-data:

networks:
  web-scraper:
    driver: bridge